### PR TITLE
[#9768] - Send Test Mail button - Ajax call has always smtpauth = 1

### PR DESCRIPTION
**Pull request by anibalsanchez**
Pull Request for Issue #9768.

#### Summary of Changes

Send Test Mail button does not correctly evaluate "SMTP Authentication" radio. Then, mails are sent via SMTP even when "SMTP Authentication" is disabled.

Fix: smtpauth : $('input[name="jform[smtpauth]"]:checked').val(),

#### Testing Instructions

1. Fill all SMTP fields in Mail Settings for a server that requires authentication
2. Test it, click on 'Send Test Mail' button to receive an email
3. Disable "SMTP Authentication" radio
4. Test it, click on 'Send Test Mail' button ... email must not be received

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
what i do is copy/paste to http://refresh-sf.com/ and them test.

hum ... this will make merge conflicts with my PR (https://github.com/joomla/joomla-cms/pull/9685) that is because of the compressed js file.

Let's hope the maintainers merge mine first :D

**Comment by anibalsanchez** [comment]
Ok, I'll update it when your PR is merged and I'll add the compressed version based on http://refresh-sf.com/

**Comment by andrepereiradasilva** [comment]
i could do the change in my PR (is a simple one), but that will take out the RTC status

**Comment by anibalsanchez** [comment]
Sure. Once it is RTC, it is better to send new PRs and avoid rolling back

**Pull request closed without merging**
